interface: ens33 #interface name
valid_lft: 12 # valid for seconds
max_ips: 10 # max new temporary ips to assign (will be random 1-max_ips)
ip_range: # pool of ips to assign
  network: 192.36 # network part for ip address
  subnet: 216
  min: 10 # min ip in pool
  max: 45 # max ip in pool
  CIDR: 24 # subnet mask
